Import cnxcommon.ident_hash in cnxdb/__init__.py
Travis reported this error:

```
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cnxdb/__init__.py", line 20, in <module>
    cnxcommon.ident_hash,
AttributeError: 'module' object has no attribute 'ident_hash'
```

Indeed, when I tried to do this:

```
karen@yachiyo:/tmp/cnx-db$ ../py3/bin/python -c 'import cnxcommon; print(cnxcommon.ident_hash)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'cnxcommon' has no attribute 'ident_hash'
```

`import cnxcommon.ident_hash` works though.

Perhaps it's because cnxcommon/__init__.py is not empty and it doesn't include
all the submodules?

https://github.com/openstax/cnx-common/blob/ce80016f45ef99ae9f36f93d454e918b9add75fc/cnxcommon/__init__.py