Fixes to docker files and load database script (#53)
* Update requirements filename change in Dockerfile

The test requirements file was renamed from tests.txt to test.txt but
the Dockerfile was not updated.

* Change Dockerfile to not specific initdb.sh filename

The build fails with this error message:

Step 15 : COPY .dockerfiles/initdb.d/* /docker-entrypoint-initdb.d/init.sh
When using COPY with more than one source file, the destination must be a directory and end with a /

* Add docker entrypoint script to load database dump

A slim database dump can be obtained by
https://github.com/Connexions/devops/wiki/How-To%3A-Get-a-Slim-Database-Dump

If a slim database dump is in the container at /tmp/cnxarchive_dump.tar,
it will get loaded.

* Put double quotes around DB_NAME in initdb.sh

DB_NAME with hyphens causes error:

```
ERROR:  syntax error at or near "-"
LINE 1: CREATE DATABASE cnxarchive-testing OWNER cnxarchive;
                                  ^
server started
```

* Uninstall cnx-db before "pip install -e ."

There is a version of cnx-db that gets installed when "requirements/test.txt"
is installed because of cnx-archive.  We try to overwrite it with the current
version of cnx-db by doing `pip install -e .`:

```
+ pip install -e .
Obtaining file:///src
  Running setup.py (path:/src/setup.py) egg_info for package from file:///src
    zip_safe flag not set; analyzing archive contents...

    Installed /src/.eggs/pytest_runner-2.12-py2.7.egg
    warning: no files found matching '*.txt'
    warning: no previously-included files matching '*.*' found under directory 'docs/_build'
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /usr/local/lib/python2.7/dist-packages (from cnx-db==0.8.0+13.gf16e403.dirty)
Requirement already satisfied (use --upgrade to upgrade): venusian in /usr/local/lib/python2.7/dist-packages (from cnx-db==0.8.0+13.gf16e403.dirty)
Installing collected packages: cnx-db
  Running setup.py develop for cnx-db
    warning: no files found matching '*.txt'
    warning: no previously-included files matching '*.*' found under directory 'docs/_build'
    Creating /usr/local/lib/python2.7/dist-packages/cnx-db.egg-link (link to .)
    Adding cnx-db 0.8.0+13.gf16e403.dirty to easy-install.pth file
    Installing cnx-db script to /usr/local/bin

    Installed /src
Successfully installed cnx-db
```

This creates a link `/usr/local/lib/python2.7/dist-packages/cnx-db.egg-link` to
`/src/`.  However, `/usr/local/lib/python2.7/dist-packages/cnxdb` still has the
old version of cnx-db.  Looking at `sys.path`:

```
>>> sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/src', '/usr/lib/python2.7/dist-packages']
```

It finds the old version of cnx-db first.

To avoid this problem, we will uninstall cnx-db before installing the
/src/ version of it.  If cnx-db is not installed, "cnx-db is not
installed, continuing..." is printed and the build continues.

* Load session_exec.so in init_venv before using it

If session_exec.so does not exist (like in our cnx-db docker image),
after init_venv, we won't be able to connect to the database:

```
$ psql 'dbname=cnxarchive-testing user=cnxarchive password=cnxarchive host=localhost port=5432'
psql: FATAL:  could not access file "session_exec": No such file or directory
```

We can print out an error and rollback to the save point instead if
session_exec is not installed.

* Look for AS_VENV_IMPORTABLE in pytest db_init

Right now there is no way to turn off init_venv when using pytest
db_init.  init_venv does not work with our cnx-db docker image so we
need a way to turn it off.