Pin docutils to 0.14 in requirements/lint.txt (#186)
docutils 0.15 breaks bin/doc8:

```
/home/travis/build/openstax/cnx-db/.state/env/bin/python bin/doc8 README.rst docs/
Traceback (most recent call last):
  File "bin/doc8", line 8, in <module>
    import doc8.main
  File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/doc8/main.py", line 48, in <module>
    from doc8 import checks
  File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/doc8/checks.py", line 21, in <module>
    from docutils import nodes as docutils_nodes
  File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/docutils/nodes.py", line 32, in <module>
    import docutils.utils
  File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    from docutils import nodes
ImportError: cannot import name nodes
make: *** [lint] Error 1
```