Use postgres super user in migrations that require it (#71)
* Create plpython function with super user in migration

When running the migrations 20160723123620_add_sql_function_strip_html,
20170201213850_add-subcollection-metadata,
20170208213802_ident-hash-func against a database where
the user is not a super user, we see this error:

```
psycopg2.ProgrammingError: permission denied for language plpythonu
```

* Create extension pg_trgm with super user in migration

When running the migration 20160723124137
add_modules_strip_html_name_index against a database where the user is
not a super user, we see this error:

```
psycopg2.ProgrammingError: permission denied to create extension "pg_trgm"
```