Lock latest_modules when running update_latest
This is to solve a race condition in the update_latest trigger because
of two inserts happening at the same time:

```
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/subscribers.py", line 106, in baking_processor
    bake(binder, recipe_id, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/db.py", line 61, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/bake.py", line 81, in bake
    publish_composite_model(cursor, doc, binder, publisher, message)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/publish.py", line 375, in publish_composite_model
    publisher, message)
  File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/publish.py", line 208, in _insert_metadata
    cursor.execute(stmt, params)
IntegrityError: duplicate key value violates unique constraint "lastest_modules_short_id_idx"
DETAIL:  Key (short_id(uuid))=(8-Z8x306) already exists.
CONTEXT:  SQL statement "INSERT into latest_modules (
         uuid, module_ident, portal_type,
         moduleid, version, name,
         created, revised,
         abstractid, stateid, doctype, licenseid,
         submitter,submitlog, parent, language,
         authors, maintainers, licensors, parentauthors,
         google_analytics,
         major_version, minor_version,
         print_style, baked, recipe)
      VALUES (
         NEW.uuid, NEW.module_ident, NEW.portal_type,
         NEW.moduleid, NEW.version, NEW.name,
         NEW.created, NEW.revised,
         NEW.abstractid, NEW.stateid, NEW.doctype, NEW.licenseid,
         NEW.submitter, NEW.submitlog, NEW.parent, NEW.language,
         NEW.authors, NEW.maintainers, NEW.licensors, NEW.parentauthors,
         NEW.google_analytics,
         NEW.major_version, NEW.minor_version,
         NEW.print_style, NEW.baked, NEW.recipe)"
PL/pgSQL function update_latest() line 10 at SQL statement
```